spring.application.name=jobportal

# Fixes the name so you can always use "jdbc:h2:mem:testdb"
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensures the console is enabled
spring.h2.console.enabled=true

server.port=9090